#!/usr/bin/env python3
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

from __future__ import annotations

from pathlib import Path
from typing import Any

from ruamel.yaml import YAML

# Paths
ROOT = Path(__file__).resolve().parents[2]
TEST_DIR = Path(__file__).resolve().parent
WORKFLOW_PATH = ROOT / ".github" / "workflows" / "regress.yml"

# YAML round-trip config
YAML_RT = YAML(typ="rt")
YAML_RT.default_flow_style = False
YAML_RT.preserve_quotes = True
YAML_RT.width = 1_000_000
YAML_RT.indent(mapping=2, sequence=4, offset=2)
YAML_RT.explicit_start = True


def load_yaml(path: Path) -> dict[str, Any]:
    data = YAML_RT.load(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise TypeError(f"{path} must contain a YAML mapping")
    return data


def validate_test(test_name: str, test_data: dict[str, Any]) -> None:
    ci_stage = test_data["ci_stage"]
    if ci_stage not in {"pr", "merge_queue"}:
        raise ValueError(f"bad ci_stage in test '{test_name}': {ci_stage}")

    matrix = test_data.get("strategy", {}).get("matrix")
    if matrix is None:
        return
    for dim_name, values in matrix.items():
        if not isinstance(values, list):
            raise TypeError(f"matrix dimension '{dim_name}' in test '{test_name}' must be a list")


def create_job(job_data: dict[str, Any], workflow_yaml: dict[str, Any]) -> dict[str, Any]:
    gh_job_yaml: dict[str, Any] = {"runs-on": "ubuntu-latest"}

    if "timeout_minutes" in job_data:
        gh_job_yaml["timeout-minutes"] = job_data["timeout_minutes"]

    if job_data["ci_stage"] == "merge_queue":
        gh_job_yaml["if"] = (
            "(github.event_name == 'merge_group') || "
            "((github.event_name == 'push') && (github.ref_name == 'main'))"
        )

    checkout_step = workflow_yaml["jobs"]["regress-llvm"]["steps"][0].copy()
    if "checkout_with" in job_data:
        checkout_step["with"] = job_data["checkout_with"]

    mise_setup_step: dict[str, Any] = {
        "name": "Set up mise environment",
        "uses": "./.github/actions/mise-setup",
    }
    if job_data.get("toolchain_container", False):
        mise_setup_step["with"] = {"toolchain": True}

    gh_job_yaml["steps"] = [checkout_step, mise_setup_step]

    for key in ("env", "strategy"):
        if key in job_data:
            gh_job_yaml[key] = job_data[key]

    for key in ("gh_pre", "test", "gh_post"):
        if key in job_data:
            gh_job_yaml["steps"].extend(job_data[key])

    if "gh_save_artifact" in job_data:
        upload_step_template = workflow_yaml["jobs"]["never-runs"]["steps"][1]
        for artifact in job_data["gh_save_artifact"]:
            upload_with = {
                "name": artifact["artifact_name"],
                "path": artifact["path"],
            }
            if artifact.get("include-hidden-files"):
                upload_with["include-hidden-files"] = True
            upload_step = upload_step_template.copy()
            upload_step["name"] = "Upload artifact"
            upload_step.insert(
                2, "if", "((github.event_name == 'push') && (github.ref_name == 'main'))"
            )
            upload_step["with"] = upload_with
            gh_job_yaml["steps"].append(upload_step)

    return gh_job_yaml


def main() -> None:
    regress_yaml = load_yaml(TEST_DIR / "regress-gh-template.yaml")
    template_job_names = [name for name in regress_yaml["jobs"] if name != "never-runs"]
    tests = load_yaml(TEST_DIR / "regress-tests.yaml")

    for test_name, test_data in tests["tests"].items():
        validate_test(test_name, test_data)
        regress_yaml["jobs"][test_name] = create_job(test_data, regress_yaml)

    regress_yaml["jobs"]["regress-complete"] = {
        "runs-on": "ubuntu-latest",
        "needs": list(tests["tests"].keys()) + template_job_names,
        "if": "always()",
        "steps": [
            {
                "name": "exit failure",
                "if": "contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')",
                "run": "exit 1",
            },
            {
                "name": "exit success",
                "if": "!contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')",
                "run": "exit 0",
            },
        ],
    }

    # Write the generated workflow YAML to the GitHub Actions workflow file
    WORKFLOW_PATH.unlink(missing_ok=True)
    with WORKFLOW_PATH.open("w", encoding="utf-8") as output:
        output.write(
            "# This file was generated by `./bin/chore gen regress`\n"
            "# DO NOT EDIT\n"
            "# Instead, edit `tools/test/regress-tests.yaml` (preferred) or "
            "`tools/test/regress-gh-template.yaml`\n\n"
        )
        YAML_RT.dump(regress_yaml, output)


if __name__ == "__main__":
    main()
