# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# typed: false
# frozen_string_literal: true

require "pathname"
require "yaml"
require "psych"

regress_template_yaml = YAML.load_file(Pathname.new(__dir__) / "regress-gh-template.yaml")
# make a deep copy
regress_yaml = YAML.load(YAML.dump(regress_template_yaml))
tests = YAML.load_file(Pathname.new(__dir__) / "regress-tests.yaml")

# Walk the Psych YAML AST and force all 'if:' scalar values to use plain (unquoted) style.
# GitHub Actions evaluates 'if:' conditions as expressions only for plain scalars;
# quoted strings are treated as literal truthy values, bypassing the condition check.
def force_plain_if_values(node)
  case node
  when Psych::Nodes::Mapping
    node.children.each_slice(2) do |key, value|
      if key.is_a?(Psych::Nodes::Scalar) && key.value == "if" &&
         value.is_a?(Psych::Nodes::Scalar)
        value.style = Psych::Nodes::Scalar::PLAIN
      end
      force_plain_if_values(key)
      force_plain_if_values(value)
    end
  when Psych::Nodes::Sequence, Psych::Nodes::Document, Psych::Nodes::Stream
    node.children.each { |child| force_plain_if_values(child) }
  end
end

def dump_workflow(data, line_width: -1)
  visitor = Psych::Visitors::YAMLTree.create({ line_width: line_width })
  visitor << data
  tree = visitor.tree
  force_plain_if_values(tree)
  tree.yaml(nil, line_width:)
end

def create_job(job_name, job_data, workflow_yaml)
  gh_job_yaml = {
    "runs-on" => "ubuntu-latest"
  }

  if job_data.key?("timeout_minutes")
    gh_job_yaml["timeout-minutes"] = job_data["timeout_minutes"]
  end

  # Add 'if' condition before 'steps' to ensure correct YAML ordering
  if job_data["ci_stage"] == "merge_queue"
    gh_job_yaml["if"] = "(github.event_name == 'merge_group') || ((github.event_name == 'push') && (github.ref_name == 'main'))"
    # Note: plain (unquoted) style is enforced by force_plain_if_values / dump_workflow
  end

  # Create checkout step with optional custom parameters
  checkout_step = {
    "name" => "Clone Github Repo Action",
    "uses" => workflow_yaml["jobs"]["regress-llvm"]["steps"][0]["uses"]
  }
  if job_data.key?("checkout_with")
    checkout_step["with"] = job_data["checkout_with"]
  end

  # Build mise-setup step, passing toolchain: true for jobs that need the RISC-V toolchain container
  mise_setup_step = {
    "name" => "Set up mise environment",
    "uses" => "./.github/actions/mise-setup"
  }
  if job_data.fetch("toolchain_container", false)
    mise_setup_step["with"] = { "toolchain" => "true" }
  end

  gh_job_yaml["steps"] = [
    checkout_step,
    mise_setup_step
  ]

  if job_data.key?("env")
    gh_job_yaml["env"] = job_data["env"]
  end

  if job_data.key?("strategy")
    gh_job_yaml["strategy"] = job_data["strategy"]
  end

  if job_data.key?("gh_pre")
    gh_job_yaml["steps"].concat(job_data["gh_pre"])
  end

  gh_job_yaml["steps"].concat(job_data["test"])

  if job_data.key?("gh_post")
    gh_job_yaml["steps"].concat(job_data["gh_post"])
  end

  if job_data.key?("gh_save_artifact")
    job_data["gh_save_artifact"].each do |artifact|
      gh_job_yaml["steps"] << {
        "name" => "Upload artifact",
        "uses" => workflow_yaml["jobs"]["never-runs"]["steps"][1]["uses"],
        "if" => "((github.event_name == 'push') && (github.ref_name == 'main'))",
        # Note: plain (unquoted) style is enforced by force_plain_if_values / dump_workflow
        "with" => {
          "name" => artifact["artifact_name"],
          "path" => artifact["path"]
        }
      }
      if artifact["include-hidden-files"]
        gh_job_yaml["steps"].last["with"]["include-hidden-files"] = true
      end
    end
  end

  gh_job_yaml
end

tests["tests"].each do |test_name, test_data|
  if ["pr", "merge_queue"].include?(test_data["ci_stage"])
    regress_yaml["jobs"][test_name] = create_job(test_name, test_data, regress_yaml)

  else
    raise "bad ci_stage: #{test_data["ci_stage"]}"
  end
end

regress_yaml["jobs"]["regress-complete"] = {
  "runs-on" => "ubuntu-latest",
  "needs" => tests["tests"].keys + (regress_template_yaml["jobs"].keys - ["never-runs"]),
  "if" => "always()",
  "steps" => [
    {
      "name" => "exit failure",
      "if" => "contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')",
      "run" => "exit 1"
    },
    {
      "name" => "exit success",
      "if" => "!contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')",
      "run" => "exit 0"
    }
  ]
}

f = <<~FILE.strip
# This file was generated by `./bin/chore gen regress`
# DO NOT EDIT
# Instead, edit `tools/test/regress-tests.yaml` (preferred) or `tools/test/regress-gh-template.yaml`

#{dump_workflow(regress_yaml)}
FILE
File.write (Pathname.new(__dir__) / ".." / ".." / ".github" / "workflows" / "regress.yml"), "#{f}\n"
