# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `oppen` gem.
# Please instead update this file by running `bin/tapioca gem oppen`.


module Oppen
  extend ::Oppen::Mixins

  class << self
    def begin_consistent(offset: T.unsafe(nil)); end
    def begin_inconsistent(offset: T.unsafe(nil)); end
    def break(str = T.unsafe(nil), line_continuation: T.unsafe(nil), offset: T.unsafe(nil), width: T.unsafe(nil)); end
    def end; end
    def eof; end
    def line_break(line_continuation: T.unsafe(nil), offset: T.unsafe(nil)); end
    def print(config: T.unsafe(nil), new_line: T.unsafe(nil), out: T.unsafe(nil), space: T.unsafe(nil), tokens: T.unsafe(nil), width: T.unsafe(nil)); end
    def string(value, width: T.unsafe(nil)); end
    def whitespace(value); end
  end
end

class Oppen::Config
  def initialize(eager_print: T.unsafe(nil), indent_anchor: T.unsafe(nil), trim_trailing_whitespaces: T.unsafe(nil), upsize_stack: T.unsafe(nil)); end

  def eager_print?; end
  def indent_anchor; end
  def indent_anchor=(_arg0); end
  def trim_trailing_whitespaces?; end
  def upsize_stack?; end

  class << self
    def oppen; end
    def wadler(eager_print: T.unsafe(nil), trim_trailing_whitespaces: T.unsafe(nil), upsize_stack: T.unsafe(nil)); end
  end
end

module Oppen::Mixins
  def tokens_to_wadler(tokens, base_indent: T.unsafe(nil), printer_name: T.unsafe(nil), width: T.unsafe(nil)); end
  def upsize_circular_array(arr, offset); end
end

class Oppen::PrintStack
  def initialize(width, new_line, config, space, out); end

  def buffer; end
  def config; end
  def erase(count = T.unsafe(nil)); end
  def genspace; end
  def handle_begin(token, token_width); end
  def handle_break(token, token_width, trim_on_break: T.unsafe(nil)); end
  def handle_end; end
  def handle_string(token, token_width); end
  def indent(amount); end
  def items; end
  def new_line; end
  def output; end
  def pop; end
  def print(token, token_width, trim_on_break: T.unsafe(nil)); end
  def print_new_line(amount); end
  def push(print_stack_entry); end
  def space; end
  def top; end
  def width; end
  def write(obj); end
end

class Oppen::PrintStack::PrintStackEntry
  def initialize(offset, break_type); end

  def break_type; end
  def offset; end
end

class Oppen::Printer
  extend ::Oppen::Mixins

  def initialize(width, new_line, config = T.unsafe(nil), space = T.unsafe(nil), out = T.unsafe(nil)); end

  def advance_left(token, token_width); end
  def advance_right; end
  def check_stack(depth); end
  def check_stream; end
  def config; end
  def handle_begin(token); end
  def handle_break(token); end
  def handle_end(token); end
  def handle_eof; end
  def handle_string(token); end
  def left; end
  def left_total; end
  def output; end
  def print(token); end
  def print_stack; end
  def right; end
  def right_total; end
  def scan_stack; end
  def size; end
  def tokens; end
end

class Oppen::ScanStack
  extend ::Oppen::Mixins

  def initialize(size, config); end

  def bottom; end
  def decrement(index); end
  def empty?; end
  def increment(index); end
  def length; end
  def pop; end
  def pop_bottom; end
  def push(value); end
  def top; end
  def update_indexes(offset); end
end

class Oppen::Token
  def width; end
end

class Oppen::Token::Begin < ::Oppen::Token
  def initialize(break_type: T.unsafe(nil), offset: T.unsafe(nil)); end

  def break_type; end
  def offset; end
end

class Oppen::Token::Break < ::Oppen::Token
  def initialize(str = T.unsafe(nil), line_continuation: T.unsafe(nil), offset: T.unsafe(nil), width: T.unsafe(nil)); end

  def line_continuation; end
  def offset; end
  def str; end
  def to_s; end
  def width; end
end

class Oppen::Token::EOF < ::Oppen::Token; end
class Oppen::Token::End < ::Oppen::Token; end

class Oppen::Token::LineBreak < ::Oppen::Token::Break
  def initialize(line_continuation: T.unsafe(nil), offset: T.unsafe(nil)); end
end

class Oppen::Token::LineBreak::LineBreakString
  def length; end
end

class Oppen::Token::String < ::Oppen::Token
  def initialize(value, width: T.unsafe(nil)); end

  def to_s; end
  def value; end
  def width; end
end

class Oppen::Token::Whitespace < ::Oppen::Token::String; end
Oppen::VERSION = T.let(T.unsafe(nil), String)

class Oppen::Wadler
  def initialize(base_indent: T.unsafe(nil), config: T.unsafe(nil), indent: T.unsafe(nil), new_line: T.unsafe(nil), out: T.unsafe(nil), space_gen: T.unsafe(nil), whitespace: T.unsafe(nil), width: T.unsafe(nil)); end

  def add_missing_begin_and_end; end
  def angles(padding: T.unsafe(nil), **kwargs, &block); end
  def angles_break_both(**kwargs, &_arg1); end
  def angles_break_none(**kwargs, &_arg1); end
  def backticks(**kwargs, &_arg1); end
  def braces(padding: T.unsafe(nil), **kwargs, &block); end
  def braces_break_both(**kwargs, &_arg1); end
  def braces_break_none(**kwargs, &_arg1); end
  def brackets(padding: T.unsafe(nil), **kwargs, &block); end
  def brackets_break_both(**kwargs, &_arg1); end
  def brackets_break_none(**kwargs, &_arg1); end
  def break(line_continuation: T.unsafe(nil)); end
  def breakable(str = T.unsafe(nil), line_continuation: T.unsafe(nil), width: T.unsafe(nil)); end
  def concat(*args, **kwargs, &_arg2); end
  def config; end
  def consistent(*_arg0, **_arg1, &_arg2); end
  def current_indent; end
  def do; end
  def group(break_type = T.unsafe(nil), delim: T.unsafe(nil), indent: T.unsafe(nil)); end
  def group_close; end
  def group_open(break_type: T.unsafe(nil), indent: T.unsafe(nil)); end
  def inconsistent(*_arg0, **_arg1, &_arg2); end
  def indent_close(indent: T.unsafe(nil)); end
  def indent_open(indent: T.unsafe(nil)); end
  def lines(*args, **kwargs, &_arg2); end
  def nest(delim: T.unsafe(nil), indent: T.unsafe(nil)); end
  def nest_close(indent: T.unsafe(nil)); end
  def nest_open(indent: T.unsafe(nil)); end
  def new_line; end
  def out; end
  def output; end
  def parens(padding: T.unsafe(nil), **kwargs, &block); end
  def parens_break_both(**kwargs, &_arg1); end
  def parens_break_none(**kwargs, &_arg1); end
  def quote_double(**kwargs, &_arg1); end
  def quote_single(**kwargs, &_arg1); end
  def separate(args, sep, breakable: T.unsafe(nil), break_pos: T.unsafe(nil), break_type: T.unsafe(nil), indent: T.unsafe(nil), force_break: T.unsafe(nil), line_continuation: T.unsafe(nil)); end
  def show_print_commands(**kwargs); end
  def space; end
  def space_gen; end
  def surround(lft, rgt, **opts); end
  def text(value, width: T.unsafe(nil)); end
  def tokens; end
  def whitespace; end
  def width; end
  def wrap(&blk); end
end

class Oppen::Wadler::Wrap
  def initialize(blk); end

  def end; end
  def method_missing(meth, *_arg1, **_arg2, &_arg3); end
  def when(cond, &blk); end

  private

  def respond_to_missing?(meth, include_private); end
end
