# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `ruby_tree_sitter` gem.
# Please instead update this file by running `bin/tapioca gem ruby_tree_sitter`.


class Object < ::BasicObject
  include ::Kernel
  include ::PP::ObjectMixin
  include ::Udb::Helpers::WavedromUtil

  private

  def array_split_like_rust(array, &_arg1); end
end

module TreeSitter
  extend ::TreeSitter::Mixins::Language

  private

  def quantifier_name(_arg0); end

  class << self
    def lang(name); end
    def quantifier_name(_arg0); end
  end
end

TreeSitter::ENV_PARSERS = T.let(T.unsafe(nil), T.untyped)
module TreeSitter::Encoding; end
TreeSitter::Encoding::UTF16 = T.let(T.unsafe(nil), Symbol)
TreeSitter::Encoding::UTF8 = T.let(T.unsafe(nil), Symbol)

class TreeSitter::Input
  def initialize(*_arg0); end

  def inspect; end
  def payload; end
  def payload=(_arg0); end
  def to_s; end
end

class TreeSitter::InputEdit
  def inspect; end
  def new_end_byte; end
  def new_end_byte=(_arg0); end
  def new_end_point; end
  def new_end_point=(_arg0); end
  def old_end_byte; end
  def old_end_byte=(_arg0); end
  def old_end_point; end
  def old_end_point=(_arg0); end
  def start_byte; end
  def start_byte=(_arg0); end
  def start_point; end
  def start_point=(_arg0); end
  def to_s; end
end

TreeSitter::LANGUAGE_VERSION = T.let(T.unsafe(nil), Integer)
TreeSitter::LIBDIRS = T.let(T.unsafe(nil), Array)

class TreeSitter::Language
  def ==(_arg0); end
  def abi_version; end
  def field_count; end
  def field_id_for_name(_arg0); end
  def field_name_for_id(_arg0); end
  def next_state(_arg0, _arg1); end
  def symbol_count; end
  def symbol_for_name(_arg0, _arg1); end
  def symbol_name(_arg0); end
  def symbol_type(_arg0); end
  def version; end

  private

  def load(_arg0, _arg1); end

  class << self
    def load(_arg0, _arg1); end
  end
end

class TreeSitter::LanguageLoadError < ::TreeSitter::TreeSitterError; end

class TreeSitter::Logger
  def initialize(*_arg0); end

  def format; end
  def format=(_arg0); end
  def inspect; end
  def payload; end
  def payload=(_arg0); end
  def printf(*_arg0); end
  def puts(*_arg0); end
  def to_s; end
  def write(*_arg0); end
end

TreeSitter::MIN_COMPATIBLE_LANGUAGE_VERSION = T.let(T.unsafe(nil), Integer)
module TreeSitter::Mixins; end

module TreeSitter::Mixins::Language
  def ext; end
  def language(name); end

  private

  def lib_dirs; end
  def search_for_lib(name); end
  def search_lib_message; end
end

class TreeSitter::Node
  include ::Enumerable

  def ==(_arg0); end
  def [](*keys); end
  def brk(out, vertical); end
  def changed?; end
  def child(_arg0); end
  def child_by_field_id(_arg0); end
  def child_by_field_name(_arg0); end
  def child_count; end
  def descendant_count; end
  def descendant_for_byte_range(_arg0, _arg1); end
  def descendant_for_point_range(_arg0, _arg1); end
  def each(&_arg0); end
  def each_field; end
  def each_named; end
  def edit(_arg0); end
  def end_byte; end
  def end_point; end
  def eq?(_arg0); end
  def error?; end
  def extra?; end
  def fetch(*keys); end
  def field?(field); end
  def field_name_for_child(_arg0); end
  def fields; end
  def first_child_for_byte(_arg0); end
  def first_named_child_for_byte(_arg0); end
  def grammar_symbol; end
  def grammar_type; end
  def has_error?; end
  def inspect; end
  def language; end
  def method_missing(method_name, *_args, &_arg2); end
  def missing?; end
  def named?; end
  def named_child(_arg0); end
  def named_child_count; end
  def named_descendant_for_byte_range(_arg0, _arg1); end
  def named_descendant_for_point_range(_arg0, _arg1); end
  def next_named_sibling; end
  def next_parse_state; end
  def next_sibling; end
  def null?; end
  def parent; end
  def parse_state; end
  def prev_named_sibling; end
  def prev_sibling; end
  def sexpr(indent: T.unsafe(nil), width: T.unsafe(nil), source: T.unsafe(nil), vertical: T.unsafe(nil)); end
  def sexpr_recur(indent: T.unsafe(nil), width: T.unsafe(nil), out: T.unsafe(nil), source: T.unsafe(nil), vertical: T.unsafe(nil)); end
  def start_byte; end
  def start_point; end
  def symbol; end
  def to_a; end
  def to_s; end
  def to_str; end
  def type; end

  private

  def respond_to_missing?(*args); end
end

TreeSitter::Node::LINE_ANNOTATION = T.let(T.unsafe(nil), Regexp)

class TreeSitter::Parser
  def cancellation_flag; end
  def cancellation_flag=(_arg0); end
  def included_ranges; end
  def included_ranges=(_arg0); end
  def language; end
  def language=(_arg0); end
  def logger; end
  def logger=(_arg0); end
  def parse(_arg0, _arg1); end
  def parse_string(_arg0, _arg1); end
  def parse_string_encoding(_arg0, _arg1, _arg2); end
  def print_dot_graphs(_arg0); end
  def reset; end
end

class TreeSitter::ParserNotFoundError < ::TreeSitter::TreeSitterError; end
class TreeSitter::ParserVersionError < ::TreeSitter::TreeSitterError; end

class TreeSitter::Point
  def column; end
  def column=(_arg0); end
  def inspect; end
  def row; end
  def row=(_arg0); end
  def to_s; end
end

module TreeSitter::Quantifier; end
TreeSitter::Quantifier::ONE = T.let(T.unsafe(nil), Integer)
TreeSitter::Quantifier::ONE_OR_MORE = T.let(T.unsafe(nil), Integer)
TreeSitter::Quantifier::ZERO = T.let(T.unsafe(nil), Integer)
TreeSitter::Quantifier::ZERO_OR_MORE = T.let(T.unsafe(nil), Integer)
TreeSitter::Quantifier::ZERO_OR_ONE = T.let(T.unsafe(nil), Integer)

class TreeSitter::Query
  def initialize(_arg0, _arg1); end

  def capture_count; end
  def capture_name_for_id(_arg0); end
  def capture_names; end
  def capture_quantifier_for_id(_arg0, _arg1); end
  def capture_quantifiers; end
  def disable_capture(_arg0); end
  def disable_pattern(_arg0); end
  def general_predicates; end
  def pattern_count; end
  def pattern_guaranteed_at_step?(_arg0); end
  def predicates_for_pattern(_arg0); end
  def property_predicates; end
  def property_settings; end
  def start_byte_for_pattern(_arg0); end
  def string_count; end
  def string_value_for_id(_arg0); end
  def text_predicates; end

  private

  def parse_property; end
  def process(source); end
end

class TreeSitter::QueryCapture
  def index; end
  def inspect; end
  def node; end
  def to_s; end
end

class TreeSitter::QueryCaptures
  include ::Enumerable

  def initialize(cursor, query, src); end

  def each(&_arg0); end
end

class TreeSitter::QueryCreationError < ::TreeSitter::TreeSitterError; end

class TreeSitter::QueryCursor
  def captures(query, node, src); end
  def exceed_match_limit?; end
  def exec(_arg0, _arg1); end
  def match_limit; end
  def match_limit=(_arg0); end
  def matches(query, node, src); end
  def max_start_depth=(_arg0); end
  def next_capture; end
  def next_match; end
  def remove_match(_arg0); end
  def set_byte_range(_arg0, _arg1); end
  def set_point_range(_arg0, _arg1); end

  class << self
    def exec(_arg0, _arg1); end
  end
end

module TreeSitter::QueryError; end
TreeSitter::QueryError::Capture = T.let(T.unsafe(nil), Integer)
TreeSitter::QueryError::Field = T.let(T.unsafe(nil), Integer)
TreeSitter::QueryError::Language = T.let(T.unsafe(nil), Integer)
TreeSitter::QueryError::NONE = T.let(T.unsafe(nil), Integer)
TreeSitter::QueryError::NodeType = T.let(T.unsafe(nil), Integer)
TreeSitter::QueryError::Structure = T.let(T.unsafe(nil), Integer)
TreeSitter::QueryError::Syntax = T.let(T.unsafe(nil), Integer)

class TreeSitter::QueryMatch
  def capture_count; end
  def captures; end
  def id; end
  def inspect; end
  def nodes_for_capture_index(index); end
  def pattern_index; end
  def satisfies_text_predicate?(query, src); end
  def to_s; end

  private

  def node_text(node, text); end
end

class TreeSitter::QueryMatches
  include ::Enumerable

  def initialize(cursor, query, src); end

  def each(&_arg0); end
  def each_capture_hash(&_arg0); end
end

class TreeSitter::QueryPredicate
  def initialize(operator, args); end

  def args; end
  def args=(_arg0); end
  def operator; end
  def operator=(_arg0); end
end

class TreeSitter::QueryPredicateStep
  def inspect; end
  def to_s; end
  def type; end
  def type=(_arg0); end
  def value_id; end
  def value_id=(_arg0); end
end

TreeSitter::QueryPredicateStep::CAPTURE = T.let(T.unsafe(nil), Symbol)
TreeSitter::QueryPredicateStep::DONE = T.let(T.unsafe(nil), Symbol)
TreeSitter::QueryPredicateStep::STRING = T.let(T.unsafe(nil), Symbol)

class TreeSitter::Range
  def end_byte; end
  def end_byte=(_arg0); end
  def end_point; end
  def end_point=(_arg0); end
  def inspect; end
  def start_byte; end
  def start_byte=(_arg0); end
  def start_point; end
  def start_point=(_arg0); end
  def to_s; end
end

class TreeSitter::SymbolNotFoundError < ::TreeSitter::TreeSitterError; end
module TreeSitter::SymbolType; end
TreeSitter::SymbolType::ANONYMOUS = T.let(T.unsafe(nil), Symbol)
TreeSitter::SymbolType::AUXILIARY = T.let(T.unsafe(nil), Symbol)
TreeSitter::SymbolType::REGULAR = T.let(T.unsafe(nil), Symbol)
TreeSitter::TREESITTER_VERSION = T.let(T.unsafe(nil), String)

class TreeSitter::TextPredicateCapture
  def initialize(type, fst, snd, positive, match_all); end

  def fst; end
  def match_all?; end
  def positive?; end
  def snd; end
  def type; end

  class << self
    def any_string(*_arg0, **_arg1, &_arg2); end
    def eq_capture(*_arg0, **_arg1, &_arg2); end
    def eq_string(*_arg0, **_arg1, &_arg2); end
    def match_string(*_arg0, **_arg1, &_arg2); end
  end
end

TreeSitter::TextPredicateCapture::ANY_STRING = T.let(T.unsafe(nil), Integer)
TreeSitter::TextPredicateCapture::EQ_CAPTURE = T.let(T.unsafe(nil), Integer)
TreeSitter::TextPredicateCapture::EQ_STRING = T.let(T.unsafe(nil), Integer)
TreeSitter::TextPredicateCapture::MATCH_STRING = T.let(T.unsafe(nil), Integer)

class TreeSitter::Tree
  def copy; end
  def edit(_arg0); end
  def included_ranges; end
  def language; end
  def print_dot_graph(_arg0); end
  def root_node; end
  def root_node_with_offset(_arg0, _arg1); end

  private

  def changed_ranges(_arg0, _arg1); end
  def finalizer; end

  class << self
    def changed_ranges(_arg0, _arg1); end
    def finalizer; end
  end
end

class TreeSitter::TreeCursor
  def initialize(_arg0); end

  def copy; end
  def current_depth; end
  def current_descendant_index; end
  def current_field_id; end
  def current_field_name; end
  def current_node; end
  def goto_descendant(_arg0); end
  def goto_first_child; end
  def goto_first_child_for_byte(_arg0); end
  def goto_first_child_for_point(_arg0); end
  def goto_last_child; end
  def goto_next_sibling; end
  def goto_parent; end
  def goto_previous_sibling; end
  def reset(_arg0); end
  def reset_to(_arg0); end
end

class TreeSitter::TreeSitterError < ::Exception; end
TreeSitter::VERSION = T.let(T.unsafe(nil), String)
