# typed: false

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `strscan` gem.
# Please instead update this file by running `bin/tapioca gem strscan`.


Object::ScanError = StringScanner::Error

class StringScanner
  def initialize(*_arg0); end

  def <<(_arg0); end
  def [](_arg0); end
  def beginning_of_line?; end
  def bol?; end
  def captures; end
  def charpos; end
  def check(_arg0); end
  def check_until(_arg0); end
  def concat(_arg0); end
  def eos?; end
  def exist?(_arg0); end
  def fixed_anchor?; end
  def get_byte; end
  def getch; end
  def inspect; end
  def match?(_arg0); end
  def matched; end
  def matched?; end
  def matched_size; end
  def named_captures; end
  def peek(_arg0); end
  def peek_byte; end
  def pointer; end
  def pointer=(_arg0); end
  def pos; end
  def pos=(_arg0); end
  def post_match; end
  def pre_match; end
  def reset; end
  def rest; end
  def rest?; end
  def rest_size; end
  def scan(_arg0); end
  def scan_byte; end
  def scan_full(_arg0, _arg1, _arg2); end
  def scan_integer(base: T.unsafe(nil)); end
  def scan_until(_arg0); end
  def search_full(_arg0, _arg1, _arg2); end
  def size; end
  def skip(_arg0); end
  def skip_until(_arg0); end
  def string; end
  def string=(_arg0); end
  def terminate; end
  def unscan; end
  def values_at(*_arg0); end

  private

  def initialize_copy(_arg0); end
  def scan_base10_integer; end
  def scan_base16_integer; end

  class << self
    def must_C_version; end
  end
end

StringScanner::Id = T.let(T.unsafe(nil), String)
StringScanner::Version = T.let(T.unsafe(nil), String)
