# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `tty-spinner` gem.
# Please instead update this file by running `bin/tapioca gem tty-spinner`.


module TTY; end
module TTY::Formats; end
TTY::Formats::FORMATS = T.let(T.unsafe(nil), Hash)

class TTY::Spinner
  include ::TTY::Formats
  include ::MonitorMixin

  def initialize(*args); end

  def attach_to(multispinner); end
  def auto_spin; end
  def clear_line; end
  def done?; end
  def duration; end
  def error(stop_message = T.unsafe(nil)); end
  def error?; end
  def execute_job; end
  def format; end
  def hide_cursor; end
  def interval; end
  def job(&work); end
  def job?; end
  def join(timeout = T.unsafe(nil)); end
  def kill; end
  def message; end
  def next_char; end
  def on(name, &block); end
  def output; end
  def pause; end
  def paused?; end
  def redraw_indent; end
  def reset; end
  def resume; end
  def row; end
  def run(stop_message = T.unsafe(nil), &block); end
  def spin; end
  def spinning?; end
  def start; end
  def stop(stop_message = T.unsafe(nil)); end
  def success(stop_message = T.unsafe(nil)); end
  def success?; end
  def tokens; end
  def update(tokens); end

  private

  def emit(name, *args); end
  def execute_on_line; end
  def fetch_format(token, property); end
  def replace_tokens(string); end
  def tty?; end
  def write(data, clear_first = T.unsafe(nil)); end
end

TTY::Spinner::CROSS = T.let(T.unsafe(nil), String)
TTY::Spinner::CURSOR_LOCK = T.let(T.unsafe(nil), Monitor)
TTY::Spinner::ECMA_CSI = T.let(T.unsafe(nil), String)
TTY::Spinner::MATCHER = T.let(T.unsafe(nil), Regexp)

class TTY::Spinner::Multi
  include ::Enumerable
  include ::MonitorMixin
  extend ::Forwardable

  def initialize(*args); end

  def auto_spin; end
  def create_spinner(pattern_or_spinner, options); end
  def done?; end
  def each(*args, **_arg1, &block); end
  def empty?(*args, **_arg1, &block); end
  def error; end
  def error?; end
  def length(*args, **_arg1, &block); end
  def line_inset(line_no); end
  def next_row; end
  def on(key, &callback); end
  def pause; end
  def register(pattern_or_spinner, **options, &job); end
  def resume; end
  def rows; end
  def spin; end
  def stop; end
  def success; end
  def success?; end
  def top_spinner; end

  private

  def done_handler; end
  def emit(key, *args); end
  def error_handler; end
  def observe(spinner); end
  def spin_handler; end
  def success_handler; end
  def throttle; end
end

TTY::Spinner::Multi::DEFAULT_INSET = T.let(T.unsafe(nil), Hash)
class TTY::Spinner::NotSpinningError < ::StandardError; end
TTY::Spinner::TICK = T.let(T.unsafe(nil), String)
TTY::Spinner::VERSION = T.let(T.unsafe(nil), String)
