# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `udb_helpers` gem.
# Please instead update this file by running `bin/tapioca gem udb_helpers`.


# source://udb_helpers//lib/udb_helpers/backend_helpers.rb#13
class String
  include ::Comparable

  # source://udb_helpers//lib/udb_helpers/backend_helpers.rb#19
  def sanitize; end
end

module Udb::Helpers
  class << self
    # source://udb_helpers//lib/udb_helpers/version.rb#9
    def version; end
  end
end

# source://udb_helpers//lib/udb_helpers/backend_helpers.rb#355
module Udb::Helpers::AntoraUtils
  class << self
    # source://udb_helpers//lib/udb_helpers/backend_helpers.rb#377
    def resolve_links(path_or_str); end
  end
end

# source://udb_helpers//lib/udb_helpers/backend_helpers.rb#281
module Udb::Helpers::AsciidocUtils
  class << self
    # source://udb_helpers//lib/udb_helpers/backend_helpers.rb#293
    def resolve_links(path_or_str); end
  end
end

# source://udb_helpers//lib/udb_helpers/backend_helpers.rb#93
module Udb::Helpers::TemplateHelpers
  include ::Udb::Helpers::WavedromUtil

  # source://udb_helpers//lib/udb_helpers/backend_helpers.rb#259
  def anchor_for_non_isa_spec(name); end

  # source://udb_helpers//lib/udb_helpers/backend_helpers.rb#252
  def anchor_for_udb_doc_cov_pt(org, id); end

  # source://udb_helpers//lib/udb_helpers/backend_helpers.rb#218
  def anchor_for_udb_doc_csr(name); end

  # source://udb_helpers//lib/udb_helpers/backend_helpers.rb#225
  def anchor_for_udb_doc_csr_field(csr_name, field_name); end

  # source://udb_helpers//lib/udb_helpers/backend_helpers.rb#198
  def anchor_for_udb_doc_ext(ext_name); end

  # source://udb_helpers//lib/udb_helpers/backend_helpers.rb#205
  def anchor_for_udb_doc_ext_param(ext_name, param_name); end

  # source://udb_helpers//lib/udb_helpers/backend_helpers.rb#244
  def anchor_for_udb_doc_idl_func(name); end

  # source://udb_helpers//lib/udb_helpers/backend_helpers.rb#212
  def anchor_for_udb_doc_inst(name); end

  # source://udb_helpers//lib/udb_helpers/backend_helpers.rb#231
  def anchor_for_udb_doc_mmr(name); end

  # source://udb_helpers//lib/udb_helpers/backend_helpers.rb#238
  def anchor_for_udb_doc_mmr_field(mmr_name, field_name); end

  # source://udb_helpers//lib/udb_helpers/backend_helpers.rb#266
  def anchor_inside_idl_inst_code(inst_name, id); end

  # source://udb_helpers//lib/udb_helpers/backend_helpers.rb#187
  def link_into_idl_inst_code(inst_name, id); end

  # source://udb_helpers//lib/udb_helpers/backend_helpers.rb#179
  def link_to_udb_doc_cov_pt(org, id); end

  # source://udb_helpers//lib/udb_helpers/backend_helpers.rb#146
  def link_to_udb_doc_csr(csr_name); end

  # source://udb_helpers//lib/udb_helpers/backend_helpers.rb#153
  def link_to_udb_doc_csr_field(csr_name, field_name); end

  # source://udb_helpers//lib/udb_helpers/backend_helpers.rb#125
  def link_to_udb_doc_ext(ext_name); end

  # source://udb_helpers//lib/udb_helpers/backend_helpers.rb#133
  def link_to_udb_doc_ext_param(ext_name, param_name, link_text); end

  # source://udb_helpers//lib/udb_helpers/backend_helpers.rb#172
  def link_to_udb_doc_idl_func(func_name); end

  # source://udb_helpers//lib/udb_helpers/backend_helpers.rb#140
  def link_to_udb_doc_inst(inst_name); end

  # source://udb_helpers//lib/udb_helpers/backend_helpers.rb#159
  def link_to_udb_doc_mmr(mmr_name); end

  # source://udb_helpers//lib/udb_helpers/backend_helpers.rb#166
  def link_to_udb_doc_mmr_field(mmr_name, field_name); end

  # source://udb_helpers//lib/udb_helpers/backend_helpers.rb#99
  def partial(template_pname, inputs = T.unsafe(nil)); end

  private

  # source://udb_helpers//lib/udb_helpers/backend_helpers.rb#272
  def check_no_periods(s); end
end

# source://udb_helpers//lib/udb_helpers/backend_helpers.rb#22
module Udb::Helpers::WavedromUtil
  # source://udb_helpers//lib/udb_helpers/backend_helpers.rb#23
  def fix_entities(text); end

  # source://udb_helpers//lib/udb_helpers/backend_helpers.rb#31
  def json_dump_with_hex_literals(data); end

  # source://udb_helpers//lib/udb_helpers/backend_helpers.rb#43
  def process_wavedrom(json_data); end
end
