// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Full sidebar structure is defined in Phase 13.
// For now, auto-generate from the docs/ directory so the site builds.
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
