#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause-Clear
# Copyright (c) 2023 RISC-V International

import argparse
import logging
import os
import sys

# Add parent directory to path to import generator.py
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from generator import load_instructions_with_metadata, parse_match

logging.basicConfig(level=logging.INFO, format="%(levelname)s:: %(message)s")


def calculate_mask(match_str):
    """Convert the bit pattern string to a mask (1 for fixed bits, 0 for variable bits)."""
    return int("".join("0" if c == "-" else "1" for c in match_str), 2)


def generate_overlap_header(instr_dict, metadata_dict, output_file):
    overlaps = []

    names = sorted(instr_dict.keys())
    for i in range(len(names)):
        name_a = names[i]
        match_str_a = instr_dict[name_a]["match"]
        match_val_a = parse_match(match_str_a)
        mask_val_a = calculate_mask(match_str_a)
        exts_a = set(metadata_dict[name_a]["extensions"])

        for j in range(i + 1, len(names)):
            name_b = names[j]
            match_str_b = instr_dict[name_b]["match"]
            match_val_b = parse_match(match_str_b)
            mask_val_b = calculate_mask(match_str_b)
            exts_b = set(metadata_dict[name_b]["extensions"])

            # Check if instructions come from completely different extensions
            if exts_a.isdisjoint(exts_b):
                # Check for encoding overlap
                if (match_val_a & mask_val_b) == (match_val_b & mask_val_a):
                    overlaps.append((name_a, list(exts_a), name_b, list(exts_b)))

    # Format overlaps for output
    output_lines = [
        "/* SPDX-" + "License-Identifier: BSD-3-Clause-Clear */",
        "/* Copyright (c) 2023 RISC-V International */",
        "/*",
        " * This file is auto-generated by riscv-unified-db",
        " */",
        "",
        "// Overlapping instructions",
    ]

    declared = set()
    for name_a, exts_a, name_b, exts_b in overlaps:
        for ext in exts_a:
            # Handle instructions ending in _rv32
            base_name_a = name_a.replace(".", "_")
            if base_name_a.endswith("_rv32"):
                base_name_a = base_name_a[:-5]
            decl_a = f"DECLARE_OVERLAP_INSN({base_name_a}, EXT_{ext.upper()})"
            if decl_a not in declared:
                output_lines.append(decl_a)
                declared.add(decl_a)
        for ext in exts_b:
            base_name_b = name_b.replace(".", "_")
            if base_name_b.endswith("_rv32"):
                base_name_b = base_name_b[:-5]
            decl_b = f"DECLARE_OVERLAP_INSN({base_name_b}, EXT_{ext.upper()})"
            if decl_b not in declared:
                output_lines.append(decl_b)
                declared.add(decl_b)

    with open(output_file, "w", encoding="utf-8") as f:
        f.write("\n".join(output_lines) + "\n")

    logging.info(f"Generated {output_file} with {len(declared)} overlap declarations")


def parse_args():
    parser = argparse.ArgumentParser(description="Generate RISC-V overlap instructions header")
    parser.add_argument(
        "--inst-dir",
        default="../../../arch/inst/",
        help="Directory containing instruction YAML files",
    )
    parser.add_argument(
        "--output",
        default="overlap_list.out.h",
        help="Output filename (default: overlap_list.out.h)",
    )
    parser.add_argument(
        "--include-all",
        "-a",
        action="store_true",
        help="Include all instructions, ignoring extension filtering",
    )
    parser.add_argument("--debug", "-d", action="store_true", help="Enable debug logging")
    parser.add_argument(
        "--extensions",
        "-e",
        nargs="+",
        default=[],
        help="List of extensions to include",
    )
    parser.add_argument(
        "--arch",
        default="BOTH",
        choices=["RV32", "RV64", "BOTH"],
        help="Target architecture (RV32, RV64, or BOTH). Default is BOTH.",
    )

    return parser.parse_args()


def main():
    args = parse_args()

    if args.debug:
        logging.getLogger().setLevel(logging.DEBUG)

    # Load instructions
    logging.info(f"Loading instructions from {args.inst_dir}")
    instr_dict, metadata_dict = load_instructions_with_metadata(
        args.inst_dir, args.extensions, include_all=args.include_all, target_arch=args.arch
    )

    # Generate overlap list
    generate_overlap_header(instr_dict, metadata_dict, args.output)


if __name__ == "__main__":
    main()
