# typed: false
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# frozen_string_literal: true

# Auto-generated by bin/chore update z3 — do not edit manually
module Udb
  Z3_VERSION = "z3-4.16.0"
end
