# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# typed: true
# frozen_string_literal: true

require "fileutils"
require "pathname"
require "sorbet-runtime"
require "tty-exit"
require "udb/cfg_arch"

require_relative "../../common_opts"
require_relative "../../defines"

module UdbGen
  # Generate a GDB target description (XML) for a fully configured UDB config.
  #
  # GDB can load an extended register description with "set tdesc filename", and a
  # remote stub can serve the same document over the qXfer:features:read packet.
  # Out of the box GDB only knows the base GPRs for RISC-V, so a config-specific
  # description is what teaches a debugger about the CSRs a given hart implements.
  #
  # Format reference:
  #   https://sourceware.org/gdb/current/onlinedocs/gdb.html/Target-Description-Format.html
  #   https://sourceware.org/gdb/current/onlinedocs/gdb.html/RISC_002dV-Features.html
  class GenCfgGdbXmlOptions < SubcommandWithCommonOptions
    include TTY::Exit

    NAME = "cfg-gdb-xml"

    # GDB's standard RISC-V feature names.
    CPU_FEATURE = "org.gnu.gdb.riscv.cpu"
    FPU_FEATURE = "org.gnu.gdb.riscv.fpu"
    VIRTUAL_FEATURE = "org.gnu.gdb.riscv.virtual"
    CSR_FEATURE = "org.gnu.gdb.riscv.csr"
    VECTOR_FEATURE = "org.gnu.gdb.riscv.vector"

    sig { void }
    def initialize
      super(name: NAME, desc: "Generate a GDB target description XML from a fully configured UDB config")
    end

    usage \
      command: NAME,
      desc: "Generate a GDB target description (XML) derived from a fully configured UDB YAML config",
      example: <<~EXAMPLE
        Generate a GDB target description for the rv64 config, printed to stdout
          $ #{File.basename($PROGRAM_NAME)} #{NAME} -c rv64

        Generate a GDB target description for the rv64 config, written to a file
          $ #{File.basename($PROGRAM_NAME)} #{NAME} -c rv64 -o rv64-target.xml

        Load the result in GDB
          (gdb) set tdesc filename rv64-target.xml
      EXAMPLE

    option :output do
      T.bind(self, TTY::Option::Parameter::Option)
      short "-o"
      long "--output=file"
      desc "Output file path (default: stdout)"
      convert :path
    end

    sig { returns(String) }
    def generate_xml
      unless cfg_arch.fully_configured?
        exit_with(:data_err, "Config '#{cfg_arch.name}' is not fully configured. Only fully configured configs are supported.\n")
      end

      lines = []
      lines << '<?xml version="1.0"?>'
      lines << '<!DOCTYPE target SYSTEM "gdb-target.dtd">'
      lines.concat(header_comment)
      lines << '<target version="1.0">'
      lines << "  <architecture>riscv:rv#{mxlen}</architecture>"
      emit_cpu_feature(lines, mxlen)
      emit_fpu_feature(lines)
      emit_vector_feature(lines)
      emit_virtual_feature(lines)
      emit_csr_feature(lines, mxlen)
      lines << "</target>"
      lines << ""

      lines.join("\n")
    end

    sig { override.params(argv: T::Array[String]).returns(T.noreturn) }
    def run(argv)
      parse(argv)

      if params[:help]
        Kernel.print help
        exit_with(:success)
      end

      if params.errors.any?
        exit_with(:usage_error, "#{params.errors.summary}\n\n#{help}")
      end

      unless params.remaining.empty?
        exit_with(:usage_error, "Unknown arguments: #{params.remaining}\n")
      end

      xml = generate_xml

      if params[:output].nil?
        $stdout.write(xml)
      else
        FileUtils.mkdir_p(params[:output].dirname)
        File.write(params[:output], xml)
        Udb.logger.info "Generated GDB target description: #{params[:output]}"
      end

      exit_with(:success)
    end

    private

    sig { returns(T::Array[String]) }
    def header_comment
      [
        "<!--",
        # REUSE-IgnoreStart
        "  SPDX-License-Identifier: BSD-3-Clause-Clear",
        # REUSE-IgnoreEnd
        "",
        "  Auto-generated by riscv-unified-db (udb-gen #{NAME})",
        "  Config: #{cfg_arch.name}",
        "-->"
      ]
    end

    sig { returns(Integer) }
    def mxlen
      value = cfg_arch.mxlen
      exit_with(:data_err, "Config '#{cfg_arch.name}' does not define MXLEN.\n") if value.nil?
      T.must(value)
    end

    # RV32E/RV64E halve the general purpose register file.
    sig { returns(Integer) }
    def num_gprs = cfg_arch.ext?(:E) ? 16 : 32

    # Width of the f registers, or nil when the config has no separate FP register file.
    #
    # Zfinx and friends put floating point operands in the x registers, so a config
    # that implements them has no f registers to describe even though it has FP CSRs.
    sig { returns(T.nilable(Integer)) }
    def flen
      return nil if cfg_arch.ext?(:Zfinx) || cfg_arch.ext?(:Zdinx) || cfg_arch.ext?(:Zhinx)

      return 128 if cfg_arch.ext?(:Q)
      return 64 if cfg_arch.ext?(:D)
      return 32 if cfg_arch.ext?(:F)

      nil
    end

    sig { returns(T.nilable(Integer)) }
    def vlen
      return nil unless cfg_arch.ext?(:V)

      value = cfg_arch.param_values["VLEN"]
      value.is_a?(Integer) ? value : nil
    end

    sig { params(lines: T::Array[String], mxlen: Integer).void }
    def emit_cpu_feature(lines, mxlen)
      lines << %(  <feature name="#{CPU_FEATURE}">)
      num_gprs.times do |i|
        lines << %(    <reg name="x#{i}" bitsize="#{mxlen}" type="int" group="general"/>)
      end
      lines << %(    <reg name="pc" bitsize="#{mxlen}" type="code_ptr" group="general"/>)
      lines << "  </feature>"
    end

    sig { params(lines: T::Array[String]).void }
    def emit_fpu_feature(lines)
      width = flen
      return if width.nil?

      lines << %(  <feature name="#{FPU_FEATURE}">)
      32.times do |i|
        lines << %(    <reg name="f#{i}" bitsize="#{width}" type="#{float_type(width)}" group="float"/>)
      end
      lines << "  </feature>"
    end

    # fflags, frm and fcsr are deliberately left to the CSR feature. GDB allows them in
    # either place, and sourcing them from the config's CSR list keeps a single
    # definition rather than risking a duplicate register name.
    sig { params(width: Integer).returns(String) }
    def float_type(width)
      case width
      when 32 then "ieee_single"
      when 64 then "ieee_double"
      else "int"
      end
    end

    sig { params(lines: T::Array[String]).void }
    def emit_vector_feature(lines)
      width = vlen
      return if width.nil?

      lines << %(  <feature name="#{VECTOR_FEATURE}">)
      32.times do |i|
        lines << %(    <reg name="v#{i}" bitsize="#{width}" type="int" group="vector"/>)
      end
      lines << "  </feature>"
    end

    sig { params(lines: T::Array[String]).void }
    def emit_virtual_feature(lines)
      lines << %(  <feature name="#{VIRTUAL_FEATURE}">)
      lines << %(    <reg name="priv" bitsize="8" type="int"/>)
      lines << "  </feature>"
    end

    sig { params(lines: T::Array[String], mxlen: Integer).void }
    def emit_csr_feature(lines, mxlen)
      csrs = cfg_arch.implemented_csrs.sort_by(&:address)
      return if csrs.empty?

      # regnum is left off deliberately. GDB numbers an unnumbered register one above
      # its predecessor, so emitting the features in a fixed order is enough, and it
      # avoids baking in a numbering that would have to track GDB's internal map.
      lines << %(  <feature name="#{CSR_FEATURE}">)
      csrs.each do |csr|
        lines << %(    <reg name="#{csr.name}" bitsize="#{csr_bitsize(csr, mxlen)}" type="int"/>)
      end
      lines << "  </feature>"
    end

    # Width a debugger actually sees when it reads the CSR.
    #
    # UDB records the architectural width, which for the counters is 64 even on RV32.
    # A CSR access is only MXLEN bits wide though, and on RV32 the upper half of a
    # 64-bit counter is a separate CSR (mcycle/mcycleh), so clamp to MXLEN rather than
    # describing a register GDB could never read in one go.
    sig { params(csr: T.untyped, mxlen: Integer).returns(Integer) }
    def csr_bitsize(csr, mxlen)
      length = csr.length(mxlen) || csr.max_length
      [length, mxlen].min
    end
  end
end
